name: Bug
description: "Report a Bug"
title: "Bug Report"
labels: ["bug"]
projects: []
assignees: []
body:
- type: input
  id: bugtitle
  attributes:
    label: "The Bug"
    description: "Please describe the Bug in detail"
  validations:
    required: true
- type: checkboxes
  id: checked
  attributes:
    label: Agreement
    options:
      - label: I have accepted the TOS!
      required: true
