name: Bug
description: "Report a Bug"
title: "Bug Report"
labels: ["bug"]
projects: []
assignees: []
body:
- type: inpit
  id: markone
  attributes:
    value: "## Welcome!"
- type: markdown
  id: marktwoo
  attributes:
    value: |
      Thanks for taking the time to fill out this bug! If you need real-time help, join us on Discord.
