name: Edit
description: Edit DNS Record of a Subdomain
title: "Edit"
labels: []
projects: []
assignees: []
body:
  - type: input
    id: domain
    attributes:
      label: Subdomain Name
      description: What subdomain do you want to edit? ex. something.is-probably.gay
      value: ".is-probably.gay"
    validations:
      required: true
