name: Get Info
description: Get Info on a Subdomain
title: "Get Info"
labels: []
projects: []
assignees: []
body:
  - type: input
    id: domain
    attributes:
      label: Subdomain Name
      description: What subdomain do you want to get info on? ex. etwas.vienna.skin
      value: ".vienna.skin"
    validations:
      required: true
