name: "Bug Report"

on:
  issues:
    types: [opened]

jobs:
  Register:
    runs-on: ubuntu-latest
    if: github.event.issue.title == 'List'
    permissions:
      issues: write
    steps:

    - name: Checkout
      uses: actions/checkout@v2.3.1

    - name: Report the Bug
    env:
        EVENT_ISSUE_BODY: ${{ github.event.issue.body }}
        EVENT_USER_LOGIN: ${{ github.event.issue.user.login }}
    
      run: |
            npm i cloudflare
            node --no-deprecation list > data.csv
            cat data.csv
            comment=$(cut -d "|" -f 2 data.csv)
            reason=$(cut -d "|" -f 1 data.csv)
            gh issue edit https://github.com/AusiPlayz/vienna.skin/issues/${{ github.event.issue.number }} -t "🌈 Bug Report $EVENT_USER_LOGIN" --add-label "bug"
            gh issue close https://github.com/AusiPlayz/vienna.skin/issues/${{ github.event.issue.number }} --comment "${comment//"\\n"/$'\n'}" --reason "$reason"
