name: "Register Subdomain"

on:
  issues:
    types: [opened]

jobs:
  Register:
    runs-on: ubuntu-latest
    if: github.event.issue.title == 'Register'
    permissions:
      issues: write
    steps:

    - name: Checkout
      uses: actions/checkout@v2.3.1
      
    - name: Register Subdomain
      env:
        EVENT_ISSUE_BODY: ${{ github.event.issue.body }}
        EVENT_USER_LOGIN: ${{ github.event.issue.user.login }}
        CF_TOKEN: "c58844f210cce608fe5ad0f78b9b6e6071170"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
            npm i cloudflare
            node --no-deprecation register > data.csv
            cat data.csv
            comment=$(cut -d "|" -f 2 data.csv)
            reason=$(cut -d "|" -f 1 data.csv)
            domain=$(cut -d "|" -f 3 data.csv)
            gh issue edit https://github.com/AusiPlayz/vienna.skin/issues/${{ github.event.issue.number }} -t "🛠 Register $domain" --add-label "domain register"
            if [ "$reason" = "completed" ]
              then
                gh issue edit https://github.com/AusiPlayz/vienna.skin/issues/${{ github.event.issue.number }} --add-label "success"
              else
                gh issue edit https://github.com/AusiPlayz/vienna.skin/issues/${{ github.event.issue.number }} --add-label "failed"
            fi
            gh issue close https://github.com/AusiPlayz/vienna.skin/issues/${{ github.event.issue.number }} --comment "$comment" --reason "$reason"
