name: "Register Subdomain"

on:
  issues:
    types: [opened]

jobs:
  Register:
    runs-on: ubuntu-latest
    if: github.event.issue.title == 'Register'
    permissions:
      issues: write
    steps:

    - name: Checkout
      uses: actions/checkout@v2.3.1
      
    - name: Register Subdomain
      env:
        EVENT_ISSUE_BODY: ${{ github.event.issue.body }}
        EVENT_USER_LOGIN: ${{ github.event.issue.user.login }}
        CF_TOKEN: ${{ secrets.CF_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
            
            gh issue edit https://github.com/AusiPlayz/vienna.skin/issues/${{ github.event.issue.number }} -t "🛠 Register $domain" --add-label "domain register"
            if [ "$reason" = "completed" ]
              then
                gh issue edit https://github.com/AusiPlayz/vienna.skin/issues/${{ github.event.issue.number }} --add-label "success"
              else
                gh issue edit https://github.com/AusiPlayz/vienna.skin/issues/${{ github.event.issue.number }} --add-label "failed"
            fi
            gh issue close https://github.com/AusiPlayz/vienna.skin/issues/${{ github.event.issue.number }} --comment "$comment" --reason "$reason"
